:- dynamic(level_reward/2).
:- dynamic(exp_fishing/1).
:- dynamic(level_fishing/1).
:- dynamic(fishing_equip/1).
:- dynamic(isInHouse/1).
:- dynamic(playerInventory/1).
:- dynamic(map_object/3).
:- dynamic(isInMarket/1).
:- dynamic(specialty/1).
:- dynamic(level_fishing/1).
:- dynamic(level_farming/1).
:- dynamic(level_ranching/1).
:- dynamic(level_player/1).
:- dynamic(exp_fishing/1).
:- dynamic(exp_farming/1).
:- dynamic(exp_ranching/1).
:- dynamic(exp_total/1).
:- dynamic(gold/1).
:- dynamic(isStart/1).
:- dynamic(specialty/1).